const ADMIN_LOG_IN = "ADMIN_LOG_IN";
const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";
const OPEN_SIDE_BAR = "OPEN_SIDE_BAR";
const CLOSE_SIDE_BAR = "CLOSE_SIDE_BAR";
const LOAD_CONTRACT = "LOAD_CONTRACT";
const LOAD_CONTRACT_FAILED = "LOAD_CONTRACT_FAILED";
const SET_LOADING_WINDOW_LOADING = "SET_LOADING_WINDOW_LOADING";
const SET_LOADING_WINDOW_CLOSE = "SET_LOADING_WINDOW_CLOSE";
const SET_LOADING_WINDOW_SUCCESS = "SET_LOADING_WINDOW_SUCCESS";
const SET_LOADING_WINDOW_FAILURE = "SET_LOADING_WINDOW_FAILURE";
const SET_ELECTION_STATUS_NOT_STARTED = "SET_ELECTION_STATUS_NOT_STARTED";
const SET_ELECTION_STATUS_STARTED = "SET_ELECTION_STATUS_STARTED";
const SET_ELECTION_STATUS_COMPLETED = "SET_ELECTION_STATUS_COMPLETED";
const LOAD_CONTRACT_DATA_FAILED = "LOAD_CONTRACT_DATA_FAILED";
const START_LOADING_CONSTITUENCY_DATA = "START_LOADING_CONSTITUENCY_DATA";
const COMPLETE_LOADING_CONSTITUENCY_DATA = "COMPLETE_LOADING_CONSTITUENCY_DATA";
const FAIL_LOADING_CONSTITUENCY_DATA = "FAIL_LOADING_CONSTITUENCY_DATA";
const START_LOADING_CITIZEN_DATA = "START_LOADING_CITIZEN_DATA";
const COMPLETE_LOADING_CITIZEN_DATA = "COMPLETE_LOADING_CITIZEN_DATA";
const FAIL_LOADING_CITIZEN_DATA = "FAIL_LOADING_CITIZEN_DATA";
const START_LOADING_CANDIDATE_DATA = "START_LOADING_CANDIDATE_DATA";
const COMPLETE_LOADING_CANDIDATE_DATA = "COMPLETE_LOADING_CANDIDATE_DATA";
const FAIL_LOADING_CANDIDATE_DATA = "FAIL_LOADING_CANDIDATE_DATA";
const START_LOADING_POLLINGBOOTH_DATA = "START_LOADING_POLLINGBOOTH_DATA";
const COMPLETE_LOADING_POLLINGBOOTH_DATA = "COMPLETE_LOADING_POLLINGBOOTH_DATA";
const FAIL_LOADING_POLLINGBOOTH_DATA = "FAIL_LOADING_POLLINGBOOTH_DATA";

export default {
    ADMIN_LOG_IN,
    ADMIN_LOG_OUT,
    CLOSE_SIDE_BAR,
    LOAD_CONTRACT,
    LOAD_CONTRACT_FAILED,
    SET_LOADING_WINDOW_LOADING,
    SET_LOADING_WINDOW_CLOSE,
    SET_LOADING_WINDOW_SUCCESS,
    SET_LOADING_WINDOW_FAILURE,
    OPEN_SIDE_BAR,
    SET_ELECTION_STATUS_NOT_STARTED,
    SET_ELECTION_STATUS_STARTED,
    SET_ELECTION_STATUS_COMPLETED,
    LOAD_CONTRACT_DATA_FAILED,
    START_LOADING_CONSTITUENCY_DATA,
    COMPLETE_LOADING_CONSTITUENCY_DATA,
    FAIL_LOADING_CONSTITUENCY_DATA,
    START_LOADING_CITIZEN_DATA,
    COMPLETE_LOADING_CITIZEN_DATA,
    FAIL_LOADING_CITIZEN_DATA,
    START_LOADING_CANDIDATE_DATA,
    COMPLETE_LOADING_CANDIDATE_DATA,
    FAIL_LOADING_CANDIDATE_DATA,
    START_LOADING_POLLINGBOOTH_DATA,
    COMPLETE_LOADING_POLLINGBOOTH_DATA,
    FAIL_LOADING_POLLINGBOOTH_DATA,
}