const ADMIN_LOG_IN = "ADMIN_LOG_IN";
const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";
const OPEN_SIDE_BAR = "OPEN_SIDE_BAR";
const CLOSE_SIDE_BAR = "CLOSE_SIDE_BAR";
const LOAD_CONTRACT = "LOAD_CONTRACT";
const LOAD_CONTRACT_FAILED = "LOAD_CONTRACT_FAILED";
const SET_LOADING_WINDOW_LOADING = "SET_LOADING_WINDOW_LOADING";
const SET_LOADING_WINDOW_CLOSE = "SET_LOADING_WINDOW_CLOSE";
const SET_LOADING_WINDOW_SUCCESS = "SET_LOADING_WINDOW_SUCCESS";
const SET_LOADING_WINDOW_FAILURE = "SET_LOADING_WINDOW_FAILURE";
const SET_ELECTION_STATUS_NOT_STARTED = "SET_ELECTION_STATUS_NOT_STARTED";
const SET_ELECTION_STATUS_STARTED = "SET_ELECTION_STATUS_STARTED";
const SET_ELECTION_STATUS_COMPLETED = "SET_ELECTION_STATUS_COMPLETED";

export default {
    ADMIN_LOG_IN,
    ADMIN_LOG_OUT,
    CLOSE_SIDE_BAR,
    LOAD_CONTRACT,
    LOAD_CONTRACT_FAILED,
    SET_LOADING_WINDOW_LOADING,
    SET_LOADING_WINDOW_CLOSE,
    SET_LOADING_WINDOW_SUCCESS,
    SET_LOADING_WINDOW_FAILURE,
    OPEN_SIDE_BAR,
    SET_ELECTION_STATUS_NOT_STARTED,
    SET_ELECTION_STATUS_STARTED,
    SET_ELECTION_STATUS_COMPLETED,
}