const ADMIN_LOG_IN = "ADMIN_LOG_IN";
const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";
const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
const CONNECT_TO_NETWORK = "CONNECT_TO_NETWORK";
const CONNECT_TO_NETWORK_FAILED = "CONNECT_TO_NETWORK_FAILED";
const LOAD_CONTRACT = "LOAD_CONTRACT";
const LOAD_CONTRACT_FAILED = "LOAD_CONTRACT_FAILED";

export default {
    ADMIN_LOG_IN,
    ADMIN_LOG_OUT,
    TOGGLE_SIDE_BAR,
    CONNECT_TO_NETWORK,
    CONNECT_TO_NETWORK_FAILED,
    LOAD_CONTRACT,
    LOAD_CONTRACT_FAILED,
}